Fix circular imports in artifact_ref.py (#42)
Fix error:

```
asset config info
Traceback (most recent call last):
  File "/Users/dhars9/mambaforge/envs/amapy-test/bin/asset", line 5, in <module>
    from amapy.app import run
  File "/Users/dhars9/Roche/asset-manager/client/amapy/amapy/__init__.py", line 3, in <module>
    from .python_api.artifact_ref import ArtifactRef
  File "/Users/dhars9/Roche/asset-manager/client/amapy/amapy/python_api/artifact_ref.py", line 3, in <module>
    from amapy import ArtifactInputs, Artifact
ImportError: cannot import name 'ArtifactInputs' from partially initialized module 'amapy' (most likely due to a circular import) (/Users/dhars9/Roche/asset-manager/client/amapy/amapy/__init__.py)

```